-- 1. TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGSERIAL PRIMARY KEY,
    correo VARCHAR(100) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20),
    rol VARCHAR(50) NOT NULL,
    activo BOOLEAN DEFAULT true NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLA DE SERVICIOS
CREATE TABLE IF NOT EXISTS servicios (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    duracion_minutos INTEGER NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    activo BOOLEAN DEFAULT true NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABLA DE RESERVAS
CREATE TABLE IF NOT EXISTS reservas (
    id BIGSERIAL PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    profesional_id BIGINT NOT NULL,
    servicio_id BIGINT NOT NULL,
    fecha_hora_cita TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    estado VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reserva_cliente     FOREIGN KEY (cliente_id)     REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_profesional FOREIGN KEY (profesional_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_servicio    FOREIGN KEY (servicio_id)    REFERENCES servicios(id) ON DELETE RESTRICT
);
